---
addons:
  sonarcloud:
    branches:
      - develop
      - master
    organization: $SONARCLOUD_PROJECT_KEY
    token: $SONARCLOUD_TOKEN
dist: trusty
jdk: oraclejdk8
language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar