---
addons:
  sonarcloud:
    branches:
      - develop
      - master
    organization: $SONARCLOUD_PROJECT_KEY
    token:
      secure: $SONARCLOUD_TOKEN
dist: trusty
jdk: oraclejdk8
language: java
install:
  - mvn package
script:
  - mvn test
  - sonar-scanner